// 移植自 lyric-kit v0.6.0 src/clean/excludeRules.ts（https://github.com/SPlayer-Dev/lyric-kit），AGPL-3.0。
// 由 npm 包 lyric-kit@0.6.0 导出的 excludeKeywords / excludeRegexes 逐条生成，勿手改；升级时重新生成。
namespace MediaIsland.Services.Lyrics.Cleanup;

/// <summary>排除制作人员行的内置规则。关键词未归一化；正则原为 JavaScript 语法，这六条与 .NET 语法兼容。</summary>
internal static class LyricsCreditRules
{
    public static readonly string[] Keywords =
    [
        "版权",
        "版权运营",
        "版权所有",
        "贝斯",
        "贝斯Bass",
        "本歌曲商用授权，前往小程序",
        "编",
        "编曲",
        "编曲 Arranger",
        "编曲Arranged By",
        "编曲Arrangement",
        "编配/钢琴",
        "编曲/混音",
        "编曲/混音/制作",
        "编调",
        "编程",
        "编程播放",
        "编钟",
        "唱",
        "录",
        "混",
        "制",
        "监",
        "策划",
        "策划 Planner",
        "策划统筹",
        "策划统筹Planner and coordinator",
        "出品",
        "出品、发行",
        "出品/发行",
        "出品/发行方",
        "出品/发行公司",
        "出品方Presented by",
        "出品方Presenter",
        "出品公司",
        "出品公司Production Company",
        "出品人",
        "出品人 Publisher",
        "出品人Chief Producer",
        "出品人Presenter",
        "出品人Producer",
        "出品团队",
        "出品团队Production Team",
        "出品Present by",
        "出品方",
        "出品人/监制",
        "出品 Produced by",
        "词",
        "词 Lyricist",
        "词曲提供",
        "词曲提供Lyrics & Composition Provided by",
        "词曲提供Lyrics and Composition Provided by",
        "词曲提供Music and Lyrics Provided by",
        "词曲提供Words and Music by",
        "词曲协力",
        "词Lyrics",
        "词曲版权管理",
        "词曲",
        "词曲创作",
        "大提琴",
        "大提琴 Cello",
        "大提琴solo",
        "大提琴独奏",
        "大键琴",
        "大提",
        "大管",
        "大号",
        "大阮",
        "大笒",
        "灯光设计",
        "灯光师",
        "第二小提琴",
        "第二小提琴 Second Violin",
        "第一小提琴",
        "第一小提琴 First Violin",
        "发行",
        "发行方",
        "发行方Publisher",
        "发行公司",
        "发行人",
        "发行Distributed by",
        "发行Distribution",
        "发行Release",
        "发行Released by",
        "发行策划",
        "发布",
        "翻唱",
        "翻译",
        "封面",
        "封面插画Cover illustration",
        "封面设计",
        "封面设计 Cover Design",
        "钢琴/合成器演奏",
        "钢琴演奏",
        "钢琴",
        "钢琴 Piano",
        "钢琴/Synth",
        "钢琴/贝斯/吉他",
        "钢片琴",
        "钢鼓",
        "歌名",
        "歌手",
        "歌手 Vocal Artist",
        "歌手 Vocal",
        "工作室",
        "鼓",
        "鼓Drums",
        "鼓录音",
        "鼓录音师",
        "鼓Drum",
        "鼓技师",
        "合成器演奏",
        "合声",
        "合声编写",
        "合声演唱",
        "合作",
        "合唱 Choir",
        "合唱指挥 Choir Conductor",
        "合唱编写",
        "合成器",
        "合成贝斯",
        "和声",
        "和声 Backing Vocals",
        "和声/和声设计",
        "和声设计",
        "和声编写",
        "和声编写Backing Vocal Arrangement",
        "和声编写Backing Vocals Design",
        "和声演唱",
        "和声Backing Vocal",
        "和音",
        "和音 Bvox",
        "和音编写",
        "和声 Back Vocal",
        "和声编写/演唱",
        "和声编写/和声",
        "和声编写、和声",
        "和音 Backing Vocal",
        "混缩",
        "混音",
        "混音 Mixed by",
        "混音 Mixing Engineer",
        "混音/母带工程师",
        "混音工程师",
        "混音工程师Mixing Engineer",
        "混音师",
        "混音室",
        "混音室Mixing Studio",
        "混音、母带",
        "混音&母带",
        "混音母带",
        "混音母带棚",
        "混音录音室",
        "混音录音棚",
        "混音/母带棚",
        "混音/音编",
        "混音助理",
        "混音棚",
        "混音师 Mixing Engineer",
        "混音/母带",
        "混音/母带 Mixing/Mastering Engineer",
        "混音工作室",
        "混音工作室 Mixing Studio",
        "吉他",
        "吉他 Guitar",
        "吉他Guitars",
        "吉他录音师",
        "吉他录制录音棚",
        "吉他/贝斯",
        "吉他演奏",
        "吉他录音",
        "吉他录音室",
        "吉他技师",
        "监制",
        "监制 Deputy Executive Producer",
        "监制Chief Producer",
        "监制Executive Director",
        "监制Supervised production",
        "监唱",
        "监听工程师",
        "键盘",
        "键盘Keyboard",
        "键提琴",
        "乐队统筹",
        "乐器演奏",
        "乐团",
        "乐队总监",
        "乐杯 Glass Harp",
        "乐队 Orchestra",
        "乐队配器 Orchestrator",
        "乐器录音师 Instrumental Recording Engineer",
        "乐器录音棚 Instrumental Recording Studio",
        "乐器录音",
        "乐器录音师",
        "乐器录音室",
        "乐手",
        "乐师",
        "乐队",
        "乐谱管理员",
        "乐器技师",
        "联合策划",
        "联合出品",
        "联合出品Co-produced by",
        "联合出品Co-production",
        "联合出品Jointly Produced by",
        "联合出品Published",
        "联合推广",
        "联合出品方",
        "录/混音",
        "录音",
        "录音 Recording Engineer",
        "录音师",
        "录音师Recording Engineer",
        "录音室",
        "录音室 Recording Studio",
        "录音制作",
        "录音工程师",
        "录音工程师 Recording Engineer",
        "录音助理",
        "录音师/混音师",
        "录音棚",
        "录音棚 Recording Studio",
        "录音工作室",
        "录音工作室 Recording Studio",
        "录音室经理",
        "民乐录制",
        "鸣谢",
        "母带",
        "母带 Mastered by",
        "母带处理工程师",
        "母带工程师",
        "母带工程师Mastering Engineer",
        "母带工程室",
        "母带后期处理工程师",
        "母带后期处理工程师Mastering Engineer",
        "母带后期处理录音室",
        "母带后期处理录音室Mastering Studio",
        "母带后期制作人",
        "母带后期制作人Mastering Producer",
        "母带制作 Mastering Engineer",
        "母带 Mastering Engineer",
        "母带Mastering",
        "母带制作",
        "母带处理",
        "母带制作人",
        "母带助理",
        "母带后期",
        "母带处理制作人",
        "母带处理录音室",
        "母带录音室",
        "配唱制作人",
        "配唱制作人 Vocals Producer",
        "配唱制作人Vocal Producer",
        "配唱",
        "配唱制作 VOCAL PRODUCTION",
        "配唱制作",
        "配唱编写",
        "配器",
        "企划",
        "企划宣传",
        "企划宣传Propaganda",
        "企划营销",
        "企划制作A&R Planning",
        "企划Planning",
        "企划统筹",
        "企宣",
        "清唱处作词",
        "清唱处作曲",
        "曲",
        "曲 Composer",
        "曲绘",
        "曲版权管理方",
        "设计",
        "设计Design",
        "特别鸣谢",
        "特别鸣谢/艺人支持",
        "特别鸣谢Acknowledgement",
        "特别企划",
        "特别感谢",
        "特邀",
        "特约嘉宾",
        "特雷门琴",
        "题记",
        "题字",
        "统筹",
        "统筹Coordinator",
        "统筹Planning",
        "推广",
        "推广策划",
        "推广策划Marketing Strategy",
        "推广策划Promotion Planning",
        "推广策划Promotion Strategy",
        "推广统筹 Promotion Coordinator",
        "推广宣传",
        "推广营销 Marketing Promotion",
        "维伴音乐",
        "文案",
        "文案Copywriting",
        "弦乐",
        "弦乐 Strings",
        "弦乐编写",
        "弦乐编写Strings Arrangement",
        "弦乐监制",
        "弦乐录音师",
        "弦乐录音室",
        "弦乐录音棚",
        "弦乐录音棚 Strings Recording Studio",
        "弦乐录制",
        "弦乐四重奏",
        "弦乐录音",
        "弦乐演奏",
        "弦乐团",
        "弦乐助理",
        "项目统筹",
        "项目统筹 Project Coordinator",
        "项目策划",
        "项目企划&统筹",
        "项目总监",
        "项目统筹Project Coordination",
        "项目协力",
        "宣传",
        "宣传/推广",
        "宣推",
        "宣发",
        "宣发统筹",
        "演唱",
        "演唱 Vocal Artist",
        "演奏者",
        "艺术指导",
        "艺术指导Art Director",
        "艺人统筹",
        "艺人助理",
        "音乐项目总监Project Executive",
        "音乐制作",
        "音乐制作发行",
        "音乐制作Music Production",
        "音频编辑",
        "音频编辑 Editing Engineer",
        "音频编辑 Vocal Editing",
        "音频编辑/人声录音",
        "音频工程师",
        "音乐出品发行公司",
        "音乐混音总监",
        "音乐编辑",
        "音乐企划",
        "音乐制作助理",
        "音乐制作总监",
        "音乐总监",
        "音响总监",
        "音乐发行",
        "音乐统筹",
        "音乐制作助理 Production Assistant",
        "音响工程师",
        "音效设计",
        "音控师",
        "音序",
        "营销推广",
        "营销推广/出品/发行",
        "营销推广Marketing",
        "营销推广Marketing Promotion",
        "营销策划",
        "营销",
        "原唱",
        "原曲",
        "原编曲",
        "原声吉他 Acoustic Guitar",
        "原版权",
        "原始版权",
        "制作发行",
        "制作公司",
        "制作公司 Production",
        "制作公司/OP",
        "制作公司Produce Company",
        "制作人",
        "制作人 Producer",
        "制作人Music Producer",
        "制作人Record Producer",
        "制作统筹",
        "制作统筹Executive Producer",
        "制作团队",
        "制作助理",
        "制作",
        "制作公司&OP",
        "制谱 Music Copyist",
        "制作人/编曲",
        "制作人/作曲/编曲",
        "制作协力",
        "制作行政",
        "制作行政统筹",
        "助理",
        "助理工程师",
        "妆发",
        "妆造",
        "服装",
        "中提琴",
        "中提琴 Viola",
        "中文词",
        "中国笛",
        "中提",
        "中阮",
        "中胡",
        "专辑",
        "总策划",
        "总策划 Chief Planner",
        "总策划Chref Planner",
        "总监制 Chief Executive Producer",
        "总企划",
        "总监制",
        "作词",
        "作曲",
        "作词协力",
        "作曲/编曲",
        "作曲 Composer",
        "作词 Lyricist",
        "Acknowledgement",
        "Additional Vocal by",
        "Arranged By",
        "Arrangement",
        "Arranger",
        "Art Director",
        "Artist",
        "A&R",
        "Background Vocals by",
        "Backing Vocal",
        "Backing Vocal Arrangement",
        "Backing Vocals",
        "Backing Vocals Design",
        "Backing vocals by",
        "Bass",
        "Beatmaker",
        "Cello",
        "Chief Producer",
        "Chref Planner",
        "Co-produced by",
        "Co-Producer",
        "Co-production",
        "Composed by",
        "Composer",
        "Copywriting",
        "Cover Design",
        "Copyist",
        "Design",
        "Distributed by",
        "Distribution",
        "Drums",
        "DJ",
        "Executive Producer",
        "First Violin",
        "Foley Artist",
        "Foley",
        "Guitar",
        "Guitars",
        "Instruments by",
        "Jointly Produced by",
        "Label Courtesy",
        "Lyricist",
        "Lyrics",
        "Lyrics & Composition Provided by",
        "Lyrics and Composition Provided by",
        "Lyrics by",
        "Marketing Promotion",
        "Marketing Strategy",
        "Mastered by",
        "Mastering by",
        "Mastering Engineer",
        "Mixed by",
        "Mixing Engineer",
        "Music and Lyrics Provided by",
        "Music Production",
        "MIDI",
        "MIDI编程",
        "OP",
        "OP、SP",
        "OP/发行",
        "OP/SP",
        "Organ",
        "Performed by",
        "Planner",
        "Planner and coordinator",
        "Presented by",
        "Presenter",
        "Produce Company",
        "Produced by",
        "Producer",
        "Production Company",
        "Production Team",
        "Promotion Planning",
        "Promotion Strategy",
        "Propaganda",
        "Published by",
        "Publisher",
        "Program",
        "Programming by",
        "PGM",
        "Record Producer",
        "Recorded at",
        "Recording Engineer",
        "Recording Studio",
        "Release",
        "Released by",
        "Repertoire Owner",
        "RAP词",
        "Remix",
        "Remixer",
        "Remixed by",
        "Second Violin",
        "Songs Title",
        "SP",
        "Strings",
        "Strings Arrangement",
        "Supervised production",
        "Scratching",
        "Viola",
        "Vocal Engineer",
        "Vocal Producer",
        "Vocal production by",
        "Vocals by",
        "Vocals Produced by",
        "Vocal Direction",
        "Words and Music by",
        "Written by",
        "电脑工程",
        "商务统筹",
        "主唱",
        "伴唱",
        "伴唱 Background Vocals",
        "伴唱 Choir",
        "女声和音",
        "男声和音",
        "绞弦琴 Hurdy-Gurdy",
        "长笛 Flute",
        "声乐指导",
        "声乐编辑",
        "人声录音 Recording",
        "人声录音 Vocal Recording",
        "人声编辑Vocal Editing",
        "人声编辑 Vocal Editor",
        "人声录制录音棚",
        "打击乐 Percussion",
        "经纪公司",
        "古琴 Guqin",
        "缩混",
        "改编曲",
        "潮语指导",
        "戏曲指导",
        "品牌宣传",
        "二胡Erhu",
        "古筝Guzheng",
        "长号 Trombone",
        "小号 Trumpet",
        "小提琴 Violin",
        "古典吉他 Classical Guitar",
        "玻璃琴 Glass Harmonica",
        "电吉他/贝司",
        "电吉他",
        "电吉他 Electric Guitar",
        "电贝斯",
        "电影原声发行",
        "电贝司",
        "电贝司 Electric Bass",
        "电脑工程师",
        "电钢琴",
        "电子鼓",
        "电子打击垫",
        "电子琴",
        "主创",
        "女声",
        "男声",
        "长号",
        "长鼓",
        "声音设计师",
        "声码器",
        "人声录音",
        "人声录音师",
        "人声录音师 Vocal Recording Engineer",
        "人声录音室",
        "人声录音棚",
        "人声录音棚 Vocal Recording Studio",
        "人声 Vocal Artist",
        "人声 Vocal",
        "人声 Voice",
        "人声编辑",
        "人声录制",
        "人声后期制作",
        "人声",
        "人声/木吉他录音师",
        "人声/木吉他录音棚",
        "人声制作人",
        "人声制作",
        "人声指导",
        "打击垫",
        "古筝",
        "二胡",
        "小号",
        "小提琴",
        "小提",
        "小阮",
        "小鼓",
        "京剧演唱",
        "京胡",
        "技术支持",
        "酷狗音乐就是歌多",
        "酷狗搜索",
        "业务联系",
        "笛子",
        "笛萧",
        "木吉他",
        "木吉他 Acoustic Guitar",
        "架子鼓 Drums",
        "琵琶",
        "萨克斯",
        "唢呐",
        "指挥 Conductor",
        "行销策略",
        "木吉他录音师",
        "木吉他录音棚",
        "视觉设计",
        "视觉设计 Visual Design",
        "木吉他录制",
        "木管",
        "木琴",
        "木箱鼓",
        "木棒",
        "木鱼",
        "指挥",
        "指弹吉他",
        "尼古赫帕琴 Nyckelharpa",
        "客串",
        "童声",
        "现场乐队",
        "英文词",
        "谱曲",
        "单曲制作",
        "执行制作人",
        "协力制作人",
        "共同制作",
        "共同制作人",
        "节拍制作",
        "节拍制作人",
        "管弦乐编排",
        "管乐编写",
        "节奏编写",
        "分轨",
        "贴混",
        "杜比全景声",
        "修音师",
        "修音",
        "重混音师",
        "预制作",
        "创意制作人",
        "创意总监",
        "拟音师",
        "拟音",
        "跟踪工程师",
        "抄谱员",
        "抄谱",
        "扒谱员",
        "扒谱",
        "谱务",
        "调音师",
        "调音",
        "前台工程师",
        "厂牌",
        "唱片公司",
        "插画",
        "承办单位",
        "承办人",
        "数字编辑",
        "数字剪辑",
        "次级发行",
        "次级发行方",
        "分发行",
        "所有乐器",
        "全部乐器",
        "造型",
        "次级版权",
        "后期制作",
        "风琴",
        "哈蒙德风琴",
        "采样器",
        "采样",
        "序列器",
        "箱琴",
        "尤克里里",
        "低音吉他",
        "乌德琴",
        "班卓琴",
        "西塔琴",
        "鲁特琴",
        "曼陀林",
        "提琴",
        "低音提琴",
        "竖琴",
        "管乐",
        "铜管",
        "竹笛",
        "短笛",
        "班苏里笛",
        "哨笛",
        "单簧管",
        "竖笛",
        "低音单簧管",
        "双簧管",
        "英国管",
        "巴松",
        "短号",
        "圆号",
        "次中音号",
        "富鲁格号",
        "富鲁格",
        "定音鼓",
        "蒂姆巴尔鼓",
        "铃鼓",
        "康加鼓",
        "邦戈鼓",
        "钹",
        "镲",
        "锣",
        "沙锤",
        "三角铁",
        "响板",
        "钟琴",
        "马林巴",
        "颤音琴",
        "瑶琴",
        "玉琴",
        "扬琴",
        "阮",
        "箫",
        "洞萧",
        "笙",
        "巴乌",
        "葫芦丝",
        "手风琴",
        "六角手风琴",
        "口琴",
        "拇指琴",
        "转盘",
        "克拉维奈",
        "梅洛特隆",
        "口风琴",
        "肩背键盘",
        "簧风琴",
        "踏板钢弦吉他",
        "滑棒吉他",
        "谐振吉他",
        "十二弦吉他",
        "布祖基",
        "恰朗戈",
        "巴拉莱卡",
        "德西马",
        "齐特琴",
        "自动竖琴",
        "手摇琴",
        "拉巴卜",
        "柳琴",
        "月琴",
        "三弦",
        "高胡",
        "板胡",
        "箜篌",
        "埙",
        "排箫",
        "排笛",
        "三味线",
        "太鼓",
        "尺八",
        "伽倻琴",
        "奚琴",
        "马头琴",
        "迪吉里杜管",
        "风笛",
        "杜杜克",
        "陶笛",
        "锡笛",
        "卡洪",
        "非洲鼓",
        "金贝鼓",
        "塔布拉",
        "达布卡",
        "手碟",
        "说话鼓",
        "波德兰鼓",
        "管钟",
        "牛铃",
        "刮壶",
        "军鼓",
        "手鼓",
        "框鼓",
        "班多钮",
        "Transcriber",
        "Transcription",
        "Turntable",
        "Turntables",
    ];

    public static readonly string[] Patterns =
    [
        "(?:【.*?音乐人.*?】|\\(.*?音乐人.*?\\)|「.*?音乐人.*?」|（.*?音乐人.*?）|『.*?音乐人.*?』)",
        ".*?未经.*?不得.*?",
        "未经(?:授权|许可)",
        "^纯音乐，请欣赏$",
        "^此歌曲为没有填词的纯音乐，请您欣赏$",
        "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}",
    ];
}
