name: Build

on:
  push:
    paths:
      - 'MediaIsland/**'

jobs:
  build_app:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: List files
        run: ls

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: pwsh -ep bypass ./Tools/Publish.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./MediaIsland/cipx/*.cipx
      
      - name: Upload APP to release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "./MediaIsland/cipx/*.cipx"
          draft: true
          bodyFile: ./MediaIsland/cipx/checksums.md
          token: ${{ secrets.GITHUB_TOKEN }}